name: Create Azure Resources

on:
  push:
    branches:
      - main
    paths:
      - 'bicep/**/*.bicep'
      - '.github/workflows/infra.yml'
  workflow_dispatch:     

jobs:
  create-azure-resources:

    env:
      DEPLOYMENT_NAME: logic-app-deployment
      RESOURCE_GROUP_NAME: rg-logic-app-governance
      LOCATION: 'eastus'

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      # The build step is to be sure no errors are present
      # in the bicep template
      - name: Validate that bicep builds
        run: az bicep build -f main.bicep
        working-directory: ./bicep

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ env.LOCATION }}
          deploymentName:  ${{ env.DEPLOYMENT_NAME }}
          template: ./bicep/main.bicep
          parameters: location=${{ env.LOCATION }} resourceGroupName=${{ env.RESOURCE_GROUP_NAME }}

      # - uses: gliech/create-github-secret-action@v1
      #   name: Write Web App Name Weather API
      #   with:
      #     name: WEBAPI_WEATHER_NAME
      #     value: ${{ steps.createResources.outputs.weatherApiName }}
      #     pa_token: ${{ secrets.PA_TOKEN }}
                        


    